# ──────────────────────────────────────────────────
# Link        https://www.hackerrank.com/challenges/np-inner-and-outer/problem?isFullScreen=true
# Problem     Inner and Outer
# Difficulty  Easy
# Subdomain   Numpy
# Platform    HackerRank
# Language    python3
# Status      Accepted
# Submitted   2026-06-19, 05:09 p.m.
# Technique   numpy-linear-algebra-primitives
# Time        O(N*M)
# Space       O(N*M)
# Insight     The implementation leverages NumPy's optimized linear algebra routines to compute the inner product of two vectors and the outer product matrix directly from input arrays.
# Interview   Before: "I would iterate through the arrays to calculate the products manually." After: "Using numpy.inner and numpy.outer is more efficient, resulting in O(N*M) time complexity for the outer product, which is optimal for generating the full result matrix."
# Pitfalls    (1) Assuming the input arrays must be of equal length for the outer product, which is not a requirement for numpy.outer.  (2) Failing to account for the memory overhead of the O(N*M) matrix generated by the outer product when input arrays are very large.
# ──────────────────────────────────────────────────

import numpy as np
A = np.array(list(map(int,input().split())))
B =  np.array(list(map(int,input().split())))
print(np.inner(A,B))
print(np.outer(A,B))



